FROM registry.access.redhat.com/ubi8/python-39

ARG WORK_DIR=/app/pelorus \
    PELORUS_IMAGE_TAG="" \
    OPENSHIFT_BUILD_SOURCE="" \
    OPENSHIFT_BUILD_REFERENCE=""

ENV APP_FILE=deploytime/app.py \
    PELORUS_IMAGE_TAG=$PELORUS_IMAGE_TAG \
    OPENSHIFT_BUILD_SOURCE=$OPENSHIFT_BUILD_SOURCE \
    OPENSHIFT_BUILD_REFERENCE=$OPENSHIFT_BUILD_REFERENCE

USER root

COPY ./ $WORK_DIR

RUN dnf -y install skopeo && \
    chown -R 1001:0 $WORK_DIR

USER 1001

WORKDIR $WORK_DIR

RUN pip install -r requirements.txt && \
    pip install -e .

# TODO use array syntax
# ENTRYPOINT [ "python" ]
CMD python ${APP_FILE}
