---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: commit-time-exporter
  name: commit-time-exporter
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: commit-time-exporter:latest
  source:
    contextDir: metrics-exporters/commit-time-exporter
    git:
      ref: master
      uri: https://github.com/redhat-cop/pelorus.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secretReference:
        name: github-secret
    type: GitHub
  - type: ConfigChange
  - type: ImageChange
