---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-oauth
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: True
    auth.anonymous:
      enabled: True
  containers:
  - args:
    - '-provider=openshift'
    - '-pass-basic-auth=false'
    - '-https-address=:9091'
    - '-http-address='
    - '-email-domain=*'
    - '-upstream=http://localhost:3000'
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
    - '-tls-cert=/etc/tls/private/tls.crt'
    - '-tls-key=/etc/tls/private/tls.key'
    - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
    - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
    - '-openshift-service-account=grafana-serviceaccount'
    - '-openshift-ca=/etc/pki/tls/cert.pem'
    - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
{{- if .Values.custom_ca }}
    - -openshift-ca=/etc/prometheus/configmaps/cluster-ca-bundle/ca-bundle.crt
{{- end}}
    - '-skip-auth-regex=^/metrics'
    image: 'quay.io/openshift/origin-oauth-proxy:4.2'
    name: grafana-proxy
    ports:
      - containerPort: 9091
        name: grafana-proxy
    resources: {}
    volumeMounts:
      - mountPath: /etc/tls/private
        name: secret-grafana-k8s-tls
        readOnly: false
      - mountPath: /etc/proxy/secrets
        name: secret-grafana-k8s-proxy
        readOnly: false
{{- if .Values.custom_ca }}
      - name: configmap-cluster-ca-bundle
        readOnly: true
        mountPath: /etc/prometheus/configmaps/cluster-ca-bundle
  configMaps:
    - cluster-ca-bundle
{{- end }}
  secrets:
    - grafana-k8s-tls
    - grafana-k8s-proxy
  service:
    ports:
      - name: grafana-proxy
        port: 9091
        protocol: TCP
        targetPort: grafana-proxy
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: grafana-k8s-tls
  ingress:
    enabled: True
    targetPort: grafana-proxy
    termination: reencrypt
  client:
    preferService: True
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
  dashboardLabelSelector:
    - matchExpressions:
        - { key: "app", operator: In, values: ['grafana'] }
