{{- define "grafana.datasources" }}
  apiVersion: 1
  datasources:
    - access: "proxy"
      basicAuth: true
      basicAuthPassword: {{ .Values.internal_prometheus_basic_auth_pass }}
      basicAuthUser: "internal"
      editable: false
      jsonData:
        tlsSkipVerify: true
      name: "prometheus"
      orgId: 1
      type: "prometheus"
      url: "https://prometheus-mdt.{{ .Release.Name }}.svc:9091"
      version: 1
{{- end }}
---
apiVersion: v1
data:
  prometheus.yaml: {{ include "grafana.datasources" . | toJson | b64enc }}
kind: Secret
metadata:
  name: grafana-datasources
type: Opaque
