---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lead-time-exporter
  name: lead-time-exporter
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lead-time-exporter
    deploymentconfig: lead-time-exporter
  type: ClusterIP
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: lead-time-exporter
  name: lead-time-exporter
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: lead-time-exporter
