apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pelorus
spec:
  groups:
  - name: softwar-delivery-performance
    rules: 
    - record: sdp:lead_time:by_app
      expr: >
        deploy_timestamp - on(image_sha) group_left github_commit_timestamp
    - record: sdp:lead_time:global
      expr: >
        avg(sdp:lead_time:by_app)
