{{- define "prometheus_scrape_config"}}
  - job_name: "federated-prometheus-local"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    basic_auth:
      username: 'internal'
      password: "{{ .Values.openshift_prometheus_basic_auth_pass }}"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
        labels:
          federated_job: "federated-prometheus-local"
  {{- range .Values.extra_prometheus_hosts }}
  - job_name: "federated-prometheus-{{ .id }}"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="openshift-state-metrics"}'
    scheme: "https"
    basic_auth:
      username: 'internal'
      password: "{{ .password }}"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "{{ .hostname }}"
        labels:
          federated_job: "federated-prometheus-{{ .id }}"
  {{- end }}
{{- end }}
---
apiVersion: v1
data:
  prometheus-additional.yml: {{ include "prometheus_scrape_config" . | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
