---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator-mdt
    app.kubernetes.io/version: v0.33.0
  name: prometheus-operator-mdt
