---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-pelorus
  name: prometheus-pelorus-htpasswd
type: Opaque
data:
  auth: "{{ (lookup "v1" "Secret" "openshift-monitoring" "prometheus-k8s-htpasswd").data.auth }}"