{{- if .Values.bucket_access_point }}
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-pelorus
spec:
  ports:
  - name: web-tls
    port: 9092
    protocol: TCP
    targetPort: web-tls
  selector:
    app: thanos-query
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-pelorus-sidecar
spec:
  ports:
  - name: thanos
    port: 10902
    protocol: TCP
    targetPort: 10902
  - name: thanos-grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    app: prometheus
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-pelorus-store
spec:
  ports:
  - name: thanos
    port: 10902
    protocol: TCP
    targetPort: 10902
  - name: thanos-grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    app: thanos-store
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
{{- end }}
