{{- if .Values.bucket_access_point }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      volumes:
      - name: thanos-store
        emptyDir: {}
      - name: thanos-config-store
        secret:
          secretName: thanos-objstore-config
      - name: cert-volume
        configMap:
          name: trusted-certs
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:v0.8.1
        args:
        - "store"
        - "--log.level=info"
        - "--grpc-address=:10901"
        - "--http-address=:10902"
        - "--objstore.config-file=/thanos-config-store/thanos.yaml"
        - "--data-dir=/thanos-store"
        ports:
        - name: query-http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - mountPath: /thanos-store
          name: thanos-store
        - mountPath: /thanos-config-store
          name: thanos-config-store
        - mountPath: /etc/ssl/certs/service-ca.crt
          subPath: service-ca.crt
          name: cert-volume
{{- end }}
