apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  displayName: Basic Python Tekton App
  metadata:
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
parameters:
- name: PROJECT_NAME
  description: "Project Name"