---
apiVersion: project.openshift.io/v1
kind: ProjectRequest
displayName: Basic Python Tekton App
metadata:
  name: basic-python-tekton
  creationTimestamp: null
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-role
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - "images"
  verbs:
  - "get"
  - "patch"
- apiGroups:
  - route.openshift.io
  resources:
  - "routes"
  verbs:
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: basic-python-tekton
