---
apiVersion: project.openshift.io/v1
kind: ProjectRequest
displayName: Basic Python Tekton App
metadata:
  name: basic-python-tekton
  creationTimestam: null
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: debug
spec:
  workspaces:
    - name: debug
  steps:
  - name: list-workspace-files
    image: ubuntu
    command:
    - /bin/bash
    args:
    - -c
    - |
      set -ex
      find /workspace
