apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: service-account-request
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: pipeline-role-binding-${PROJECT_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pipeline-role
  subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ${PROJECT_NAMESPACE}
parameters:
- name: PROJECT_NAMESPACE
  description: "Namespace"