version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Docker - exporters
  - package-ecosystem: "docker"
    directory: "/exporters"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  # Docker - operator
  - package-ecosystem: "docker"
    directory: "/pelorus-operator"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
