name-template: 'v$RESOLVED_VERSION 🎉'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'kind/feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
      - 'fix'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'kind/documentation'
  - title: '🛠️ Misc. Improvements'
    label: 'maintenance'
  - title: '🔡 Other changes'
  - title: '📦 Operator Updates'
    label: 'compatibility'
    collapse-after: 5

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

# Version template: v"$MAJOR.$MINOR.$PATCH"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
