version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_build:
      - find _readthedocs/html
      - find .cache

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
 configuration: mkdocs.yml
