version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_build:
      - find _readthedocs/html
      - find .cache

python:
  install:
    - requirements: docs/requirements.txt
