version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_build:
      - python -m mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml -v

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

mkdocs:
 configuration: mkdocs.yml