= Contributing to Pelorus
:toc:
:toc-title:
:toc-placement!:

Here is a list of helpful topics and areas that could use your help.

toc::[]

== Types of contributions we’re looking for
* Resolving issues
* Contributing to Documentation
* Revise language to be more approachable and friendly

== Ground rules & expectations

Before we get started, here are a few things we expect from you (and
that you should expect from others):

* Be kind and thoughtful in your conversations around this project. We
all come from different backgrounds and projects, which means we likely
have different perspectives on "how open source is done". Try to
listen to others rather than convince them that your way is correct.
* If you open a pull request, please ensure that your contribution
passes all tests. If there are test failures, you will need to address
them before we can merge your contribution.
* When adding content, please consider if it is widely valuable. Please
don’t add references or links to things you or your employer have
created as others will do so if they appreciate it.

== Getting set up for local development

Refer to the link:./README.md[Readme] for the prerequisites on setting up and running Pelorus.

### Prerequisites

Before deploying the tooling, you must have the following prepared

* An OpenShift 3.11 or higher Environment
* A machine from which to run the install (usually your laptop)
** The OpenShift Command Line Tool (oc)
** https://github.com/helm/helm/releases[Helm 3]
** jq
  
### Deployment Instructions

To deploy pelorus, run the following script from within the root repository directory

```
./runhelm.sh
```

Pelorus also has additional (optional) exporters that can be deployed to gather additional data and integrate with external systems. Consult the docs for each exporter below:

* link:./exporters/committime/README.md[Commit Time Exporter]
* Deploy Time (Coming Soon)

### Adding extra prometheus instances

By default, this tool will pull in data from the cluster in which it is running. The tool also supports collecting data across mulitple OpenShift clusters. In order to do this, we need to point the Pelorus instance at these other clusters.

To do this, create a new variables file , `extra_prometheus_hosts.yaml`.  It is a yaml file with an array of entries with the following parameters:

* id - a description of the prometheus host (this will be used as a label to select metrics in the federated instance).
* hostname - the fully qualified domain name or ip address of the host with the extra prometheus instance
* password - the password used for the 'internal' basic auth account (this is provided by the k8s metrics prometheus instances in a secret).

For example:

    extra_prometheus_hosts:
      - id: "ci-1"
        hostname: "prometheus-k8s-openshift-monitoring.apps.ci-1.example.com"
        password: "<redacted>"

Once you are finished adding your extra hosts, you can update your stack by re-running the helm command above, passing your values file with `--values extra-prometheus-hosts.yaml`

```
./runhelm.sh --values extra-prometheus-hosts.yaml
```

### Cleaning Up

Cleaning up Pelorus is very simple.

    helm template --namespace pelorus pelorus ./charts/deploy/ | oc delete -f-
    
== Contributing Content

Here is a link to the General Contribution Guidelines for the Red Hat Communities of Practice. It will cover some Do's and Dont's, such as forking a repo instead of creating a new branch.
link:https://redhat-cop.github.io/contrib/[Contribution Guidelines]

If you’d like to contribute, start by searching through the GitHub
https://github.com/redhat-cop/pelorus/issues[issues] and
https://github.com/redhat-cop/pelorus/pulls[pull requests] to see
whether someone else has raised a similar idea or question.

If you don’t see your idea listed, and you think it fits into the goals
of this guide, do one of the following: * *If your contribution is
minor,* such as a typo fix, open a pull request. * *If your contribution
is major,* such as a new article or category, start by opening an issue
first. That way, other people can weigh in on the discussion before you
do any work.

