{
 "title": "DevOps / Software Delivery Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 }, "content": "# Average Lead Time" },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 }, "content": "# Deployment Frequency" },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 }, "content": "# Mean Time to Restore" },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 15, "y": 0 }, "content": "# Change Failure Rate" },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((openshift_build_complete{build=~\".+pipeline.+\"} != 0) - openshift_build_start{build=~\".+pipeline.+\"})"
    }
   ]
  },
  {
   "title": "Percent Change in Last 30 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(scalar(avg((openshift_build_complete{build=~\".+pipeline.+\"} offset $interval != 0) - openshift_build_start{build=~\".+pipeline.+\"} offset $interval) - scalar(avg((openshift_build_complete{build=~\".+pipeline.+\"} != 0) - openshift_build_start{build=~\".+pipeline.+\"} ))) / scalar(avg((openshift_build_complete{build=~\".+pipeline.+\"} offset $interval != 0) - openshift_build_start{build=~\".+pipeline.+\"} offset $interval   )))"
    }
   ]
  },
  {
   "title": "Last $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Change % in Last $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval]))-sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval] offset $interval)))/sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval] offset $interval))"
    }
   ]
  },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "From Last Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "delta",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "\ncount(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed\"} [$interval] ) > 0) / count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed|complete\"} [$interval] ) > 0)"
    }
   ]
  },
  {
   "title": "Change since previous $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed\"} [$interval] ) > 0) / count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed|complete\"} [$interval] ) > 0)) - (count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed\"} [$interval] offset $interval ) > 0) / count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed|complete\"} [$interval] offset $interval ) > 0))) / (count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed\"} [$interval] offset $interval ) > 0) / count(sum_over_time(openshift_build_status_phase{build_phase=~\"cancelled|error|failed|complete\"} [$interval] offset $interval ) > 0))"
    }
   ]
  },
  {
   "title": "Total Builds / Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(openshift_build_status_phase)"
    }
   ]
  },
  {
   "title": "Lead Time for Change",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg((openshift_build_complete{build=~\".+pipeline.+\"} != 0) - openshift_build_start{build=~\".+pipeline.+\"})"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(openshift_build_status_phase{build_phase=~\"cancelled|failed|error\"}) / sum(openshift_build_status_phase{build_phase=~\"cancelled|error|failed|complete\"})"
    }
   ]
  }
 ]
}