include::../../tools/00_0_Lab_Header.adoc[]

== {labname} Lab

In this lab, you explore the use of Network Policy to protect a simple application.

.Goals
* Isolate a Project from other projects
* Allow access from ingress controller
* Allow access between related projects

[[labexercises]]
:numbered:

== Isolate a project from other projects. Allow access from ingress controllers.

. Create a new namespace and deploy a sample application
+
[source]
----------------------------------
$ oc new-project cakephp-example
$ oc new-app cakephp-mysql-example
----------------------------------

. Get the route that was created and see that the sample app runs.
+
[source]
---------------
$ oc get routes
---------------

. Copy and paste the route into your browser and see that the app works and the counter increments when you refresh the page.

. Your project does not have any network policies yet. With no network policies in your project, any other project can access it. Once you create a network policy, only what is explicitly allowed is permitted, everything else is denied.

. Next, protect the application from being accessed by other projects. To do this create a network policy that just defines accepting connections between pods within this project. Using this policy will automatically shut off access from other projects.
+
[source]
--------------------------------------------------------
$ mkdir $HOME/netpol

$ cat <<EOF >$HOME/netpol/allow-same-namespace.yml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
EOF
$ oc create -n cakephp-example -f $HOME/netpol/allow-same-namespace.yml
--------------------------------------------------------

. Try refreshing your browser and see that the app no longer works. The router is no longer able to contact the application pods.

. The OpenShift^(R)^ ingress controllers needs access to your sample app for it to work. The ingress controllers are found in the `openshift-ingress` project. Create a network policy that allows it.
+
NOTE: Policy Groups for the ingress controllers differ, depending upon the infrastructure. `network.openshift.io/policy-group=ingress` label is used in AWS and other clouds.
+
First verify that the `network.openshift.io/policy-group=ingress` label is present on the openshift-ingress namespace.

ifeval::[{show_solution} == true]
[source]
-------------------------------------------------------------
$ oc get namespace openshift-ingress -o yaml

apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c24,c4
    openshift.io/sa.scc.supplemental-groups: 1000560000/10000
    openshift.io/sa.scc.uid-range: 1000560000/10000
  creationTimestamp: "2020-08-10T16:18:55Z"
  labels:
    name: openshift-ingress
    network.openshift.io/policy-group: ingress
    olm.operatorgroup.uid/fb2fd614-1a99-4e33-addd-6f563ab8d982: ""
    openshift.io/cluster-monitoring: "true"
  managedFields:

[...]

  name: openshift-ingress
  resourceVersion: "23742"
  selfLink: /api/v1/namespaces/openshift-ingress
  uid: b7c08b5e-9d9a-4890-9278-43db1e626431
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
-------------------------------------------------------------
endif::[]

. Then create a network policy to allow traffic from the openshift-ingress namespace by label.
+
[source]
-------------------------------------------------------------
$ cat <<EOF >$HOME/netpol/allow-openshift-ingress.yml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openshift-ingress
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
EOF
$ oc create -n cakephp-example -f $HOME/netpol/allow-openshift-ingress.yml
-------------------------------------------------------------
+
WARNING: There is currently a link:https://bugzilla.redhat.com/show_bug.cgi?id=1768608["bug"^] that will prevent this from working if your ingress controller is using `hostnetwork`, which most non-cloud platforms currently use. Run `oc patch namespace default --type=merge -p '{"metadata": {"labels": {"network.openshift.io/policy-group": "ingress"}}}'` or your environment will not work. Read the BZ for more details.

. Test the route again, see that your application is accessible again and the counter increments.

Congratulations, you successfully isolated your project.

== Allow Access Between Related Projects

In the previous exercise you deployed an all-in-one application with build, frontend, and database all in a single project. In real-world deployments these components are often broken into multiple projects managed by separate templates. In this section you create a multi-project configuration for the example CakePHP MySQL application and add NetworkPolicy to secure communications between the projects.

The multi-project application you will be working with is based on the same CakePHP example used previously and can be found at link:https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git[https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git^].

The multi-project CakePHP + MySQL example consists of three project namespaces:

* *cakephp-example-build* - Application build and image stream
* *cakephp-example-database* - Backend MySQL database
* *cakephp-example-frontend* - Application frontend web application

The project namespace names can be configured with template parameters if desired.

The following templates are provided for multi-project deployment:

[options="header",cols="25,15,60"]
|=========================================================================================================
| Template                 | Use With    | Description
| cakephp-namespaces       | `oc apply`  | Create and configure project namespaces
| cakephp-namespace-init   | `oc create` | Initialize namespaces with resources including password secrets
| cakephp-build            | `oc apply`  | Create and configure build config & image stream
| cakephp-mysql-frontend   | `oc apply`  | Create and configure frontend deployment, service, & route
| cakephp-mysql-persistent | `oc apply`  | Create and configure MySQL database deployment & service
|=========================================================================================================

=== Verify cluster-admin Access

Configuring the multi-project configuration described below requires cluster-admin access to label namespaces and create EgressNetworkPolicy resources.

. Verify your current identity using `oc whoami` and verify that you can update namespaces and create EgressNetworkPolicy using `oc auth can-i`.
+
[source]
-----------
$ oc whoami
karla
$ oc auth can-i update Namespace
yes
$ oc auth can-i create EgressNetworkPolicy
yes
-----------

=== Deploy multi-project CakePHP + MySQL Example

////
. Because of some of the labels used earlier in this course will cause a problem in this lab, you need to run the following commands before starting. This will ensure the right labels are in place on your nodes so that storage can pe provisioned correctly.
+
[source]
----
$ for i in $(oc get machine -n openshift-machine-api -o name);do oc patch $i --type=merge -p '{"spec": {"metadata": {"labels": {"failure-domain.beta.kubernetes.io/zone": "nova"}}}}' -n openshift-machine-api;done
$ for i in $(oc get machine -n openshift-machine-api -o name);do oc patch $i --type=merge -p '{"spec": {"metadata": {"labels": {"failure-domain.beta.kubernetes.io/region": "regionOne"}}}}' -n openshift-machine-api;done
$ for i in $(oc get node -l node-role.kubernetes.io/worker -o name);do oc label $i failure-domain.beta.kubernetes.io/zone-;done
----
////

. Double check that your nodes have the following labels set. If not make sure to update the MachineSets with the correct labels:
* `failure-domain.beta.kubernetes.io/zone: nova`
* `failure-domain.beta.kubernetes.io/region: regionOne`
* `topology.kubernetes.io/region: regionOne`
* `topology.kubernetes.io/zone: nova`

. Clone the Git repository link:https://github.com/redhat-gpte-devopsautomation/cakephp-ex[https://github.com/redhat-gpte-devopsautomation/cakephp-ex^] and change directory into `cakephp-ex`.
+
[source]
--------------------------------------------------------------------------
$ cd $HOME
$ git clone https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git
$ cd $HOME/cakephp-ex
--------------------------------------------------------------------------

. Review the `openshift/multi-project-templates/parameters.yml` configuration.
+
[source]
----------------------------------------------------------------------------------------
$ cat openshift/multi-project-templates/parameters.yml

NAME: "cakephp"
BUILD_NAMESPACE: "cakephp-example-build"
DATABASE_NAMESPACE: "cakephp-example-database"
FRONTEND_NAMESPACE: "cakephp-example-frontend"
IMAGE_NAMESPACE: "openshift"
VOLUME_CAPACITY: "1Gi"
#CAKEPHP_SECRET_SALT: "...generate..."
#CAKEPHP_SECRET_TOKEN: "...generate..."
#DATABASE_NAME: ""
#DATABASE_USER: "cakephp"
#DATABASE_PASSWORD: "...generate..."
#DATABASE_ROOT_PASSWORD: "...generate..."
#DATABASE_SERVICE_NAME: "mysql"
#PHP_VERSION: "7.1"
#SOURCE_REPOSITORY_URL: "https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git"
#SOURCE_REPOSITORY_REF: ""
#CONTEXT_DIR: ""
#GITHUB_WEBHOOK_SECRET: "...generate..."
#COMPOSER_MIRROR: ""
#VERSION: "latest"
----------------------------------------------------------------------------------------

. Update the PHP Version in the parameters.yml file to *7.3* and remove the comment. The file should look like this:
+
[source]
----
NAME: "cakephp"
BUILD_NAMESPACE: "cakephp-example-build"
DATABASE_NAMESPACE: "cakephp-example-database"
FRONTEND_NAMESPACE: "cakephp-example-frontend"
IMAGE_NAMESPACE: "openshift"
VOLUME_CAPACITY: "1Gi"
#CAKEPHP_SECRET_SALT: "...generate..."
#CAKEPHP_SECRET_TOKEN: "...generate..."
#DATABASE_NAME: ""
#DATABASE_USER: "cakephp"
#DATABASE_PASSWORD: "...generate..."
#DATABASE_ROOT_PASSWORD: "...generate..."
#DATABASE_SERVICE_NAME: "mysql"
PHP_VERSION: "7.3"
#SOURCE_REPOSITORY_URL: "https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git"
#SOURCE_REPOSITORY_REF: ""
#CONTEXT_DIR: ""
#GITHUB_WEBHOOK_SECRET: "...generate..."
#COMPOSER_MIRROR: ""
#VERSION: "latest"
----

. Use the `cakephp-namespaces.yml` template to create the projects using the parameters file.
+
[source]
---------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-namespaces.yml \
| oc apply -f -
---------------------------------------------------------------

. Initialize the project namespaces with secrets and persistent volume claims.
+
[source]
-----------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-namespace-init.yml \
| oc create -f -
-----------------------------------------------------------------

. Deploy the MySQL database backend.
+
[source]
-------------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-mysql-persistent.yml \
| oc apply -f -
-------------------------------------------------------------------

. Configure and trigger the application build as version "0.1".
+
[source]
---------------------------------------------------------------
$ oc process --local \
--param=VERSION=0.1 \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-build.yml \
| oc apply -f -
---------------------------------------------------------------

. Deploy application version 0.1 to the frontend namespace.
+
[source]
-----------------------------------------------------------------
$ oc process --local \
--param=VERSION=0.1 \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-mysql-frontend.yml \
| oc apply -f -
-----------------------------------------------------------------

. Get the route hostname from the `cakephp-example-frontend` namespace and test in your browser. If you did the previous section of the lab you will not be able to access the application because you don't have a network policy rule yet to allow the ingress controllers access to your projects.
ifeval::[{show_solution} == true]
+
[source]
--------------------------------------------------
$ oc get route -n cakephp-example-frontend cakephp
--------------------------------------------------
endif::[]

=== Configure NetworkPolicy to Restrict Access

. Edit the `openshift/multi-project-templates/cakephp-namespaces.yml` to add name labels to each namespace.
ifeval::[{show_solution} == true]
+
After editing `cakephp-namespaces.yml` the output of `git diff` should be similar to the output below:
+
[source]
--------------------------------------------------------------------------------------------------------------------------------
$ git diff openshift/multi-project-templates/cakephp-namespaces.yml

diff --git a/openshift/multi-project-templates/cakephp-namespaces.yml b/openshift/multi-project-templates/cakephp-namespaces.yml
index 5879cdc..983873b 100644
--- a/openshift/multi-project-templates/cakephp-namespaces.yml
+++ b/openshift/multi-project-templates/cakephp-namespaces.yml
@@ -51,11 +51,17 @@ objects:
   apiVersion: v1
   metadata:
     name: ${BUILD_NAMESPACE}
+    labels:
+      name: ${BUILD_NAMESPACE}
 - kind: Namespace
   apiVersion: v1
   metadata:
     name: ${FRONTEND_NAMESPACE}
+    labels:
+      name: ${FRONTEND_NAMESPACE}
 - kind: Namespace
   apiVersion: v1
   metadata:
     name: ${DATABASE_NAMESPACE}
+    labels:
+      name: ${DATABASE_NAMESPACE}
--------------------------------------------------------------------------------------------------------------------------------
endif::[]

. Re-process the `cakephp-namespaces.yml` template to add labels to the project namespaces.
ifeval::[{show_solution} == true]
+
[source]
---------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-namespaces.yml \
| oc apply -f -
---------------------------------------------------------------
endif::[]

. Add NetworkPolicy resource definitions to lock-down the frontend project namespace to the `openshift/multi-project-templates/cakephp-mysql-frontend.yml` template.
+
--
NetworkPolicy resources should include:

* deny-by-default
* allow-same-namespace
* allow-openshift-ingress
--
ifeval::[{show_solution} == true]
+
After editing `openshift/multi-project-templates/cakephp-mysql-frontend.yml` the output of `git diff` should be similar to the output below:
+
----------------------------------------------------------------------------------------------------------------------------------------
$ git diff openshift/multi-project-templates/cakephp-mysql-frontend.yml

diff --git a/openshift/multi-project-templates/cakephp-mysql-frontend.yml b/openshift/multi-project-templates/cakephp-mysql-frontend.yml
index 3f98000..b7ec904 100644
--- a/openshift/multi-project-templates/cakephp-mysql-frontend.yml
+++ b/openshift/multi-project-templates/cakephp-mysql-frontend.yml
@@ -206,3 +206,36 @@ objects:
   - apiGroup: rbac.authorization.k8s.io
     kind: Group
     name: system:serviceaccounts:${FRONTEND_NAMESPACE}
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: deny-by-default
+    namespace: ${FRONTEND_NAMESPACE}
+  spec:
+    podSelector: {}
+    policyTypes:
+    - Ingress
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: allow-same-namespace
+    namespace: ${FRONTEND_NAMESPACE}
+  spec:
+    podSelector:
+    policyTypes:
+    - Ingress
+    ingress:
+    - from:
+      - podSelector: {}
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: allow-openshift-ingress
+    namespace: ${FRONTEND_NAMESPACE}
+  spec:
+    podSelector: {}
+    ingress:
+    - from:
+      - namespaceSelector:
+          matchLabels:
+            network.openshift.io/policy-group: ingress
----------------------------------------------------------------------------------------------------------------------------------------
endif::[]

. Add NetworkPolicy resource definitions to lock-down the database project namespace to the `openshift/multi-project-templates/cakephp-mysql-persistent.yml` template.
+
--
NetworkPolicy resources should include:

* deny-by-default
* allow-same-namespace
* allow-cakephp
** Allow for MySQL database pods
** Allow ingress to ports 3306/tcp from cakephp-example-frontend namespace

You will need to add a FRONTEND_NAMESPACE parameter to the `cakephp-mysql-persistent.yml` template to reference the frontend namespace by name label.
--
ifeval::[{show_solution} == true]
+
After editing `openshift/multi-project-templates/cakephp-mysql-persistent.yml` the output of `git diff` should be similar to the output below:
+
--------------------------------------------------------------------------------------------------------------------------------------------
$ git diff openshift/multi-project-templates/cakephp-mysql-persistent.yml

diff --git a/openshift/multi-project-templates/cakephp-mysql-persistent.yml b/openshift/multi-project-templates/cakephp-mysql-persistent.yml
index 84e84fa..a45b6f5 100644
--- a/openshift/multi-project-templates/cakephp-mysql-persistent.yml
+++ b/openshift/multi-project-templates/cakephp-mysql-persistent.yml
@@ -33,6 +33,13 @@ parameters:
     The OpenShift Namespace where the Database deployment and service reside.
   required: true
   value: cakephp-example-database
+- name: FRONTEND_NAMESPACE
+  displayName: Frontend Namespace
+  description: >-
+    The OpenShift Namespace where the Frontend application deployment, route,
+    and service reside.
+  required: true
+  value: cakephp-example-frontend
 - name: IMAGE_NAMESPACE
   displayName: Image Namespace
   description: The OpenShift Namespace where the PHP S2I ImageStream resides.
@@ -139,3 +146,53 @@ objects:
           resources:
             limits:
               memory: ${MEMORY_MYSQL_LIMIT}
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: deny-by-default
+    namespace: ${DATABASE_NAMESPACE}
+  spec:
+    podSelector: {}
+    policyTypes:
+    - Ingress
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: allow-same-namespace
+    namespace: ${DATABASE_NAMESPACE}
+  spec:
+    podSelector:
+    policyTypes:
+    - Ingress
+    ingress:
+    - from:
+      - podSelector: {}
+- kind: NetworkPolicy
+  apiVersion: networking.k8s.io/v1
+  metadata:
+    name: allow-frontend-to-database
+    namespace: ${DATABASE_NAMESPACE}
+  spec:
+    podSelector:
+      matchLabels:
+        name: ${DATABASE_SERVICE_NAME}
+    ingress:
+    - from:
+      - namespaceSelector:
+          matchLabels:
+            name: ${FRONTEND_NAMESPACE}
+      ports:
+      - protocol: TCP
+        port: 3306
--------------------------------------------------------------------------------------------------------------------------------------------
endif::[]

. Re-process the `cakephp-mysql-persistent.yml` template to create the NetworkPolicy resources.
ifeval::[{show_solution} == true]
+
[source]
-------------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-mysql-persistent.yml \
| oc apply -f -
-------------------------------------------------------------------
endif::[]

. Confirm that you can now access the CakePHP example application in your web browser using the same route hostname as before.

=== Configure EgressNetworkPolicy

For the CakePHP example application the build process needs access to a number of external sources to pull images, and source code. Securing the build process of this application would require use of a proxy repository service such as Nexus and so is beyond the scope of this lab. The database and frontend namespaces require no external access and so can be secured quite simply.

. Add EgressNetworkPolicy resource definitions to lock-down the database project namespace to the `cakephp-namespaces.yml` templates. Using the `cakephp-namespaces.yml` template for these resources is appropriate because both adding labels to namespaces and defining EgressNetworkPolicy requires cluster-admin privilege.
ifeval::[{show_solution} == true]
+
[source]
---------------------------------------------------------------
$ cat <<EOF >>$HOME/cakephp-ex/openshift/multi-project-templates/cakephp-namespaces.yml
- kind: EgressNetworkPolicy
  apiVersion: network.openshift.io/v1
  metadata:
    name: default
    namespace: \${FRONTEND_NAMESPACE}
  spec:
    egress:
    - type: Deny
      to:
        cidrSelector: 0.0.0.0/0
- kind: EgressNetworkPolicy
  apiVersion: network.openshift.io/v1
  metadata:
    name: default
    namespace: \${DATABASE_NAMESPACE}
  spec:
    egress:
    - type: Deny
      to:
        cidrSelector: 0.0.0.0/0
EOF
---------------------------------------------------------------
endif::[]

. Use the updated `cakephp-namespaces.yml` template to create the EgressNetworkPolicy resources.
ifeval::[{show_solution} == true]
+
[source]
---------------------------------------------------------------
$ oc process --local \
--param-file=openshift/multi-project-templates/parameters.yml \
--ignore-unknown-parameters \
-f openshift/multi-project-templates/cakephp-namespaces.yml \
| oc apply -f -
---------------------------------------------------------------
endif::[]

. Again confirm that you can still access the CakePHP example application in your web browser using the same route hostname as before.

== Clean Up Environment

. Clean up the four projects you created.
+
[source]
------------------------------------------
$ oc delete project cakephp-example
$ oc delete project cakephp-example-build
$ oc delete project cakephp-example-database
$ oc delete project cakephp-example-frontend
------------------------------------------
