# Values file for exporter helm chart
app_name: failure-exporter
source_context_dir: exporters/
extraEnv:
- name: APP_FILE
  value: failure/app.py
source_ref: master
source_url: https://github.com/redhat-cop/pelorus.git
env_from_secrets: 
- jira-secret