{
 "title": "k8s / DevOps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Deployments",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}"
    }
   ]
  },
  {
   "title": "Deployments Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"cancelled\"}"
    }
   ]
  },
  {
   "title": "Deployments Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"cancelled\"}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  {
   "title": "Deployments Complete",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openshift_build_total{phase=\"Complete\"}) / sum(openshift_build_total)"
    }
   ]
  },
  {
   "title": "JenkinsPipelines Successful",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openshift_build_total{phase=\"Complete\", strategy=\"JenkinsPipeline\"}) / sum(openshift_build_total{strategy=\"JenkinsPipeline\"})"
    }
   ]
  }
 ]
}