{
 "title": "K8s / Custom / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
   },
   { "name": "host", "label": "host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  {
   "title": "Nodes Active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}) / count(kube_node_status_condition{condition=\"Ready\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Pods Active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason=\"Error\"} == 0) / count(kube_pod_container_info)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu{job=\"node-exporter\",mode=\"idle\"}[2m])) / count(node_cpu{job=\"node-exporter\", mode=\"idle\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(ALERTS{severity='critical', alertstate='firing'})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_time_seconds{instance=\"$node\"} - node_boot_time_seconds{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Volume Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (kube_pod_info) by (node)", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "title": "CPU Usage per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Project",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}