{
 "title": "k8s / Custom / Remediation",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Uptime Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_time_seconds{instance=\"$node\"} - node_boot_time_seconds{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\"}-node_boot_time{instance=\"$node\"}"
    }
   ]
  },
  { "title": "Control Plane Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "API Servers Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / count(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controllers\"} == 1) / count(up{job=\"kube-controllers\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controllers\"} == 1) / count(up{job=\"kube-controllers\"})) * 100"
    }
   ]
  },
  {
   "title": "API Request Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"2..\"}[5m])) / sum(rate(apiserver_request_count[5m])) * 100"
    }
   ]
  },
  { "title": "Capacity Planning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu{job=\"node-exporter\",mode=\"idle\"}[2m])) / count(node_cpu{job=\"node-exporter\", mode=\"idle\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}