{
 "title": "k8s / Custom / Storage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "persistentvolume",
    "label": "persistentvolume",
    "query": "label_values(kube_persistentvolumeclaim_info, persistentvolumeclaim)"
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Storage Allocation By Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)"
    }
   ]
  },
  {
   "title": "Number PVCs by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"}) * 100 "
    }
   ]
  },
  {
   "title": "Total Resource Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)"
    }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase == 1)"
    }
   ]
  },
  {
   "title": "Volume Status by Phase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Volume Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "volumes_queue_latency" }
   ]
  },
  {
   "title": "Storage Allocation By Volume Over Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}