{
 "title": "Software Delivery Performance - By App",
 "tags": [
  "team",
  "software-delivery-performance"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(sdp:applications, app)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Lead Time for Change: The time it takes to move from code committed to code deployed in production.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "content": "# Lead Time for Change"
  },
  {
   "type": "text",
   "description": "Deployment Frequency: How often code is deployed to production.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "content": "# Deployment Frequency"
  },
  {
   "type": "text",
   "description": "Mean Time to Restore: How long it takes to recover from a failure in production.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "content": "# Mean Time to Restore"
  },
  {
   "type": "text",
   "description": "Change Failure Rate: The percentage of deployments that cause a failure in production.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "content": "# Change Failure Rate"
  },
  {
   "title": "Lead Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdp:lead_time:by_app{app=~\".*/$app/.*\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp{app=~\".*/$app/.*\"} [$__range]) )"
    }
   ]
  },
  {
   "title": "Time to Restore",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdp:time_to_restore:by_app{app=~\".*/$app/.*\"})"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdp:change_failure_rate:by_app{app=~\".*/$app/.*\"})"
    }
   ]
  },
  {
   "title": "Lead Time for Change Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(min by (app, image_sha) (deploy_timestamp{app=~\".*/$app/.*\"} - on(app,image_sha) group_left commit_timestamp))"
    }
   ]
  },
  {
   "title": "Deployments Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp{app=~\".*/$app/.*\"} [$__range]) )"
    }
   ]
  },
  {
   "title": "Mean Time to Restore Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(failure_resolution_timestamp{app=~\".*/$app/.*\",app!=\"unknown\"} - max_over_time(failure_creation_timestamp{app=~\".*/$app/.*\",app!=\"unknown\"}[5y]))"
    }
   ]
  },
  {
   "title": "Change Failure Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(failure_creation_timestamp{app=~\".*/$app/.*\",app!=\"unknown\"}) / count(min by (app, commit, image_sha) (deploy_timestamp{app=~\".*/$app/.*\"} - on(app,image_sha) group_left(commit) commit_timestamp))"
    }
   ]
  }
 ]
}