---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    grafana: grafana
    app: grafana
  name: grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: admin
      admin_password: {{ .Values.openshift_prometheus_basic_auth_pass | default "pelorus" }}
    auth:
{{- if .Values.oauth_proxy_enabled }}
      disable_login_form: "true"
      disable_signout_menu: "true"
    auth.basic:
      enabled: "true"
    auth.proxy:
      enabled: "true"
      header_name: "X-Forwarded-User"
      header_property: "username"
      auto_sign_up: "true"
{{- else }}
      disable_login_form: "false"
      disable_signout_menu: "true"
    auth.basic:
      enabled: "true"
{{- end }}
    auth.anonymous:
      enabled: {{ .Values.grafana_anonymous_auth | default "false" | quote }}
{{- if .Values.oauth_proxy_enabled }}
  deployment:
    spec:
      template:
        spec:
          containers:
          - args:
            - '-provider=openshift'
            - '-pass-basic-auth=false'
            - '-https-address=:9091'
            - '-http-address='
            - '-email-domain=*'
            - '-upstream=http://localhost:3000'
            - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
            - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
            - '-tls-cert=/etc/tls/private/tls.crt'
            - '-tls-key=/etc/tls/private/tls.key'
            - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
            - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
            - '-openshift-service-account=grafana-sa'
            - '-openshift-ca=/etc/pki/tls/cert.pem'
            - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
{{- if .Values.custom_ca }}
            - -openshift-ca=/etc/prometheus/configmaps/cluster-ca-bundle/ca-bundle.crt
{{- end}}
            - '-skip-auth-regex=^/metrics|^/public'
            image: {{ .Values.oauth_proxy_image | default "image-registry.openshift-image-registry.svc.cluster.local:5000/openshift/oauth-proxy:v4.4" }}
            name: grafana-proxy
            ports:
              - containerPort: 9091
                name: grafana-proxy
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 100Mi
            volumeMounts:
              - mountPath: /etc/tls/private
                name: secret-grafana-k8s-tls
                readOnly: true
              - mountPath: /etc/proxy/secrets
                name: secret-grafana-k8s-proxy
                readOnly: true
          volumes:
            - name: secret-grafana-k8s-tls
              secret:
                secretName: grafana-k8s-tls
            - name: secret-grafana-k8s-proxy
              secret:
                secretName: grafana-k8s-proxy
  service:
    metadata:
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: grafana-k8s-tls
    spec:
      ports:
        - name: grafana-proxy
          port: 9091
          protocol: TCP
          targetPort: grafana-proxy
  serviceAccount:
    metadata:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
  route:
    spec:
      port:
        targetPort: grafana-proxy
      tls:
        termination: reencrypt
{{- else }}
  route:
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
{{- end }}
  client:
    preferIngress: false
