{{- if .Values.oauth_proxy_enabled }}
---
apiVersion: v1
data:
  session_secret: {{ .Values.grafana_session_secret | default (randAlphaNum 32) | b64enc }}
kind: Secret
metadata:
  name: grafana-k8s-proxy
type: Opaque
{{- end }}
