{{- if ne .Values.operator_source "redhat" }}
{{- if .Values.oauth_proxy_enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "prometheus-oauth-cookie" }}
{{- $cookieSecret := "" }}
{{- if $secret }}
{{- $cookieSecret = index $secret.data "session_secret" }}
{{- else }}
{{- $cookieSecret = .Values.prometheus_oauth_cookie_secret | default (randAlphaNum 32) | b64enc }}
{{- end }}
---
apiVersion: v1
data:
  session_secret: {{ $cookieSecret }}
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-pelorus
  name: prometheus-oauth-cookie
type: Opaque
{{- end }}
{{- end }}
