{{- if ne .Values.operator_source "redhat" }}
{{- if .Values.oauth_proxy_enabled }}
---
apiVersion: v1
data:
  auth: {{ required "openshift_prometheus_htpasswd_auth must be set when oauth_proxy_enabled is true (generate with: htpasswd -s -b -n internal <password>)" .Values.openshift_prometheus_htpasswd_auth | b64enc }}
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-pelorus
  name: prometheus-pelorus-htpasswd
type: Opaque
{{- end }}
{{- end }}
