{{- if .Values.bucket_access_point }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: pelorus-thanos
      volumes:
      - name: thanos-store
        emptyDir: {}
      - name: thanos-config-store
        secret:
          secretName: thanos-objstore-config
      - name: cert-volume
        configMap:
          name: trusted-certs
      containers:
      - name: thanos-store
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image: quay.io/thanos/thanos:{{ .Values.thanos_version | default "v0.37.2" }}
        args:
        - "store"
        - "--log.level=info"
        - "--grpc-address=:10901"
        - "--http-address=:10902"
        - "--objstore.config-file=/thanos-config-store/thanos.yaml"
        - "--data-dir=/thanos-store"
        ports:
        - name: query-http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /-/ready
            port: query-http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: query-http
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /thanos-store
          name: thanos-store
        - mountPath: /thanos-config-store
          name: thanos-config-store
        - mountPath: /etc/ssl/certs/service-ca.crt
          subPath: service-ca.crt
          name: cert-volume
{{- end }}
