{{- define "pelorus.thanos.objstore.config" }}
type: s3
config:
{{- if .Values.thanos_bucket_name }}
  bucket: {{ .Values.thanos_bucket_name | quote }}
{{- else }}
  bucket: thanos
{{- end }}
  endpoint: {{ .Values.bucket_access_point | quote}}
  access_key: {{ .Values.bucket_access_key | quote}}
  secret_key: {{ .Values.bucket_secret_access_key | quote}}
  http_config:
    insecure_skip_verify: true
{{- end }}
{{- if .Values.bucket_access_point }}
---
apiVersion: v1
data:
  thanos.yaml: {{ include "pelorus.thanos.objstore.config" . | b64enc }}
kind: Secret
metadata:
  name: thanos-objstore-config
type: Opaque
{{- end }}
