{
 "title": "Software Delivery Performance",
 "tags": [
  "global",
  "software-delivery-performance"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Software Delivery Performance\n\n\n"
  },
  {
   "title": "Software Delivery Performance Score",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "( 0\n- ( 2 * ((sdp:lead_time:global) - (sdp:lead_time:global offset $__range)) / (sdp:lead_time:global offset $__range) or vector(0) )\n+ ( 2 * (count (count_over_time (deploy_timestamp [$__range]) ) - count (count_over_time (deploy_timestamp [$__range] offset $__range) ) ) / count (count_over_time (deploy_timestamp [$__range] offset $__range) ) or vector(0) )\n- ( 2 * ((sdp:time_to_restore:global ) - (sdp:time_to_restore:global  offset $__range)) / (sdp:time_to_restore:global  offset $__range) or vector(0) ) \n- ( ((avg_over_time(sdp:change_failure_rate:global [$__range])) - (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) ) / (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) or vector(0) )\n) / 7"
    }
   ]
  },
  {
   "title": "Software Delivery Performance Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( 0\n- ( 2 * ((sdp:lead_time:global) - (sdp:lead_time:global offset $__range)) / (sdp:lead_time:global offset $__range) or vector(0) )\n+ ( 2 * (count (count_over_time (deploy_timestamp [$__range]) ) - count (count_over_time (deploy_timestamp [$__range] offset $__range) ) ) / count (count_over_time (deploy_timestamp [$__range] offset $__range) ) or vector(0) )\n- ( 2 * ((sdp:time_to_restore:global ) - (sdp:time_to_restore:global  offset $__range)) / (sdp:time_to_restore:global  offset $__range) or vector(0) ) \n- ( ((avg_over_time(sdp:change_failure_rate:global [$__range])) - (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) ) / (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) or vector(0) )\n) / 7"
    }
   ]
  },
  {
   "type": "text",
   "description": "Lead Time for Change: The time it takes to move from code commited to code deployed in production.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "content": "# Lead Time for Change"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 }, "content": "# Deployment Frequency" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 }, "content": "# Mean Time to Restore" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 }, "content": "# Change Failure Rate" },
  {
   "title": "Current interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "sdp:lead_time:global" }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "description": "Negative numbers are good here.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sdp:lead_time:global) - (sdp:lead_time:global offset $__range)) / (sdp:lead_time:global offset $__range)"
    }
   ]
  },
  {
   "title": "Current interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp [$__range]) )"
    }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count (count_over_time (deploy_timestamp [$__range]) ) - count (count_over_time (deploy_timestamp [$__range] offset $__range) ) ) / count (count_over_time (deploy_timestamp [$__range] offset $__range) )"
    }
   ]
  },
  {
   "title": "Current Interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "sdp:time_to_restore:global" }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sdp:time_to_restore:global ) - (sdp:time_to_restore:global  offset $__range)) / (sdp:time_to_restore:global  offset $__range)\n"
    }
   ]
  },
  {
   "title": "Current Interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sdp:change_failure_rate:global [$__range])"
    }
   ]
  },
  {
   "title": "Change since last interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((avg_over_time(sdp:change_failure_rate:global [$__range])) - (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) ) / (avg_over_time(sdp:change_failure_rate:global [$__range] offset $__range) ) "
    }
   ]
  },
  {
   "title": "Lead Time for Change over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "sdp:lead_time:global" }
   ]
  },
  {
   "title": "Deployments over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (count_over_time (deploy_timestamp [$__range]) )"
    }
   ]
  },
  {
   "title": "MTTR over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "sdp:time_to_restore:global" }
   ]
  },
  {
   "title": "Change Failure Rate over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sdp:change_failure_rate:global [$__range])"
    }
   ]
  },
  {
   "title": "Recent Go-Lives",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by (app) (deploy_timestamp) * 1000"
    }
   ]
  },
  {
   "title": "Untracked Commits",
   "type": "singlestat",
   "description": "This is the number of commits that are currently not being taken into account in the measures above because of missing information.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count( commit_timestamp and on (app, image_sha) deploy_timestamp )"
    }
   ]
  },
  {
   "title": "Untracked Deployments",
   "type": "singlestat",
   "description": "This is the number of deployments that are currently not being taken into account in the measures above because of missing information.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count( deploy_timestamp unless on (app, image_sha) commit_timestamp )"
    }
   ]
  },
  {
   "title": "Unknown Issues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(failure_creation_timestamp{app=\"unknown\"})"
    }
   ]
  }
 ]
}