---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-grafana
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: {{ .Release.Namespace }}
