---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-api
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
  - update
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-api
subjects:
- kind: ServiceAccount
  name: grafana-api
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-api