---
apiVersion: v1
data:
  auth: {{ .Values.openshift_prometheus_htpasswd_auth | b64enc }}
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-pelorus
  name: prometheus-pelorus-htpasswd
type: Opaque
