resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: image-registry.openshift-image-registry.svc:5000/pelorus/pelorus-operator
  newTag: latest
