apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deployment-template
metadata:
  annotations:
    description: Application template for applications built using a Jenkins Pipeline
  name: deployment-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
      app.kubernetes.io/managed-by: applier
    name: ${APPLICATION_NAME}
    namespace: ${APPLICATION_NAME}${ENV}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app.kubernetes.io/name: ${APPLICATION_NAME}
          app.kubernetes.io/instance: ${APPLICATION_NAME}
          app.kubernetes.io/component: api
          app.kubernetes.io/part-of: ${APPLICATION_NAME}
          app.kubernetes.io/managed-by: applier
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -s 'localhost:8080'
                | grep "Welcome to your static nginx application on OpenShift"
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
      app.kubernetes.io/managed-by: applier
    name: ${APPLICATION_NAME}
    namespace: ${APPLICATION_NAME}${ENV}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's service.
    labels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
      app.kubernetes.io/managed-by: applier
    name: ${APPLICATION_NAME}
    namespace: ${APPLICATION_NAME}${ENV}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Service for application.
    labels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
      app.kubernetes.io/managed-by: applier
    name: ${APPLICATION_NAME}
    namespace: ${APPLICATION_NAME}${ENV}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
      app.kubernetes.io/managed-by: applier
    name: jenkins_edit
    namespace: ${APPLICATION_NAME}${ENV}
  groupNames: null
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${SA_NAME}
    namespace: ${SA_NAMESPACE}
  userNames:
  - system:serviceaccount:${SA_NAMESPACE}:${SA_NAME}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: nginx-app
- description: The environment
  name: ENV
  required: true
- description: Name of a service account that can deploy to this project
  name: SA_NAME
  required: true
  value: jenkins
- description: Namespace of service account that can deploy to this project
  name: SA_NAMESPACE
  required: true
  value: basic-nginx-build
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
