# permissions for end users to edit pelorus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pelorus-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pelorus-operator
    app.kubernetes.io/part-of: pelorus-operator
    app.kubernetes.io/managed-by: kustomize
  name: pelorus-editor-role
rules:
- apiGroups:
  - charts.pelorus.konveyor.io
  resources:
  - pelorus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.pelorus.konveyor.io
  resources:
  - pelorus/status
  verbs:
  - get
