name: Create PR in operator market place repository
description: Create PR in redhat-openshift-ecosystem/community-operators-prod from fork
inputs:
  token:
    description: GitHub personal access token (PAT) that has write access (with repo and workflow scopes) to the fork repo
    required: true
  version:
    description: The operator version to be released, following semantic versioning
    required: true
  fork_user:
    description: The user username of the fork to open PR from
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: pip install --no-cache-dir "pydantic==2.12.5" "pydantic-settings==2.9.1" "pygithub==2.6.0"

    - name: Create marketplace PR
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_FORK_USER: ${{ inputs.fork_user }}
      run: python ${{ github.action_path }}/main.py
