name: Create PR in operator market place repository
description: Create PR in redhat-openshift-ecosystem/community-operators-prod from fork
inputs:
  token:
    description: GitHub token that has write access to fork repo
    required: true
  version:
    description: The operator version to be released, following semantic versioning
    required: true
  fork:
    description: The username of the fork to open PR from
    required: true
runs:
  using: docker
  image: Dockerfile
