name: Python Pylama Github Action
description: 'Pylama Github Action running on a python slim docker image'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
steps:
- uses: actions/checkout@master
- name: Python Pylama Github Action
  uses: Akhil325/pylama-github-action@master
  with:
    args: pylama --help
