---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pelorus-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: pelorus-exporters
    app.kubernetes.io/name: {{ .Values.app_name }}
    app.kubernetes.io/version: v1.1
  name: pelorus-exporter
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - replicationcontrollers
  verbs:
  - list
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: pelorus-exporters
    app.kubernetes.io/name: exporters
    app.kubernetes.io/version: v1.2
  name: {{ .Release.Namespace }}-pelorus-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pelorus-exporter
subjects:
- kind: ServiceAccount
  name: pelorus-exporter
  namespace: {{ .Release.Namespace }}