apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app_name }}
    deploymentconfig: {{ .Values.app_name }}
  type: ClusterIP
