apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}
    k8s-app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}
    deploymentconfig: {{ .Values.app_name }}
  type: ClusterIP
