name: Build and push exporter image to Quay.io

inputs:
  image:
    required: true
  tags:
    description: Comma separated string with the different image tags
    required: true
  quay_imagenamespace:
    required: true
  quay_username:
    required: true
  quay_password:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set variables
      shell: bash
      run: |
        echo "FULL_IMAGE_NAME=quay.io/${{ inputs.quay_imagenamespace }}/${{ inputs.image }}" >> $GITHUB_ENV
        echo "PARSED_TAGS=$(for tag in $(echo ${{ inputs.tags }} | tr "," " ");do echo -n "--tag ${{ env.FULL_IMAGE_NAME }}:$tag ";done)" >> $GITHUB_ENV

# TODO uncomment

    # - name: Login to Quay.io (docker)
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ inputs.quay_username }}
    #     password: ${{ inputs.quay_password }}
    #     registry: quay.io

    - name: Build exporter image
      shell: bash
      working-directory: ./exporters
      run: |
        docker image build ${{ env.PARSED_TAGS }} \
        --build-arg PELORUS_IMAGE_TAG="${{ env.FULL_IMAGE_NAME }}:$(echo ${{ inputs.tags }} | grep -oP 'v\d+\.\d+.\d+(-rc.\d+)?')" \
        -f Containerfile .

    - name: DEBUG
      shell: bash
      run: docker image ls -a

    # - name: Push exporter image to Quay.io
    #   shell: bash
    #   run: docker push --all-tags ${{ env.FULL_IMAGE_NAME }}
