apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: github-secret
  stringData:
    GITHUB_REPOS: ${GITHUB_REPOS}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
    GITHUB_USER: ${GITHUB_USER}
    WebHookSecretKey: ${WEBHOOK_SECRET}
parameters:
- name: GITHUB_REPOS
  value: redhat-cop/mdt-quickstart, AlyIbrahim/bitbucket-client
- name: GITHUB_USER
  required: true
- name: GITHUB_TOKEN
  required: true
- name: WEBHOOK_SECRET
  generate: expression
  from: '[A-Z0-9]{8}'
