# For details refer to the documentation:
#       https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusExporters/#env_from_secrets
#       https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterFailure/

apiVersion: v1
kind: Secret
metadata:
  name: jira-secret
  namespace: pelorus
type: Opaque
stringData:
  SERVER: "https://pelorustest.atlassian.net/" # Provide JIRA Server endpoint
  API_USER: "pelorus@jira.username.io"             # JIRA Username
  TOKEN: "secret_token"                        # JIRA Token
