#!/usr/bin/env python3

import argparse
import subprocess
import sys
from pathlib import Path

parser = argparse.ArgumentParser(
    description="Format python code or check if formatting would change (for CI)"
)
parser.add_argument(
    "--check",
    action="store_true",
    help="Check for any changes that need to be made, but don't make them (useful for CI)",
)

args = parser.parse_args()

status = 0

script_path = Path(__file__).resolve()
exporters = script_path.parent.parent / "exporters"

if args.check:
    print("\nChecking black formatting")
    cmd = ["black", "--check"]
else:
    print("\nFormatting with black")
    cmd = ["black"]
cmd.append(exporters)

print(" ".join(map(str, cmd)))
result = subprocess.run(cmd)
if result.returncode == 0:
    pass
elif result.returncode == 1:
    status = 1
else:
    sys.exit(result.returncode)

if args.check:
    print("\nChecking isort formatting")
    cmd = ["isort", "--check"]
else:
    print("\nFormatting with isort")
    cmd = ["isort"]

cmd.append(exporters)
print(" ".join(map(str, cmd)))
result = subprocess.run(cmd)
if result.returncode != 0:
    sys.exit(result.returncode)

sys.exit(status)
