#!/usr/bin/env bash

failed=0

echo 🐍 Checking python formatting
if ! make -k format-check; then
    printf "\n\n"
    echo "It looks like the formatting is bad. Try using make format." >&2
    failed=1
fi

printf "\n\n"

echo 🔍 Linting
if ! make -k lint; then
    printf "\n\n"
    echo "Linting failed. Check the above output for hints." >&2
    failed=1
fi

printf "\n\n"

if [[ failed -ne 0 ]]; then
    echo "If you must, use git commit --no-verify to bypass these checks." >&2
fi

exit $failed
