---
#From: https://raw.githubusercontent.com/integr8ly/grafana-operator/master/deploy/roles/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
roleRef:
  kind: Role
  name: grafana-operator
  apiGroup: rbac.authorization.k8s.io
