#!/usr/bin/env bash
#
# One-command demo setup: install Pelorus, seed 6 months of data, verify.
#
# Usage:
#   ./demo/setup-demo.sh           # full install + seed
#   ./demo/setup-demo.sh --seed    # seed only (skip install)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SEED_ONLY=false
[[ "${1:-}" == "--seed" ]] && SEED_ONLY=true

log() { echo "[$(date +%H:%M:%S)] $*"; }

# 1. Install (unless --seed)
if [[ "$SEED_ONLY" == "false" ]]; then
  log "Installing Pelorus..."
  bash "$SCRIPT_DIR/install.sh"
  echo ""
fi

NAMESPACE="${NAMESPACE:-pelorus}"
if [[ -z "${PELORUS_PASSWORD:-}" ]]; then
  echo "ERROR: PELORUS_PASSWORD must be set (it was generated by install.sh)." >&2
  echo "Re-run with: PELORUS_PASSWORD=<password> $0 $*" >&2
  exit 1
fi

# 2. Port-forward to webhook
log "Setting up port-forward to webhook exporter..."
lsof -ti:18080 | xargs kill 2>/dev/null || true
oc port-forward -n "$NAMESPACE" svc/webhook-exporter 18080:8080 &>/dev/null &
PF_PID=$!
trap "kill $PF_PID 2>/dev/null || true" EXIT
sleep 3

# 3. Seed 6 months of data
log "Seeding 6 months of DORA metrics..."
bash "$SCRIPT_DIR/seed-metrics.sh" http://localhost:18080

# 4. Wait for Prometheus
log "Waiting 90s for Prometheus to scrape and evaluate recording rules..."
sleep 90

# 5. Verify
log "Verifying metrics..."
GRAFANA_ROUTE=$(oc get route grafana-route -n "$NAMESPACE" -o jsonpath='{.spec.host}' 2>/dev/null || echo "")

if [[ -n "$GRAFANA_ROUTE" ]]; then
  DS_UID=$(curl -sk -u "admin:${PELORUS_PASSWORD}" "https://${GRAFANA_ROUTE}/api/datasources" 2>/dev/null \
    | python3 -c 'import sys,json; ds=json.load(sys.stdin); print(ds[0]["uid"] if ds else "")' 2>/dev/null || echo "")

  if [[ -n "$DS_UID" ]]; then
    deploys=$(curl -sk -u "admin:${PELORUS_PASSWORD}" "https://${GRAFANA_ROUTE}/api/datasources/proxy/uid/${DS_UID}/api/v1/query" \
      --data-urlencode 'query=count(deploy_timestamp)' 2>/dev/null \
      | python3 -c 'import sys,json; r=json.load(sys.stdin); print(r["data"]["result"][0]["value"][1] if r.get("data",{}).get("result") else "0")' 2>/dev/null || echo "0")

    log "  Deploys in Prometheus: $deploys"

    curl -sk -u "admin:${PELORUS_PASSWORD}" "https://${GRAFANA_ROUTE}/api/datasources/proxy/uid/${DS_UID}/api/v1/query" \
      --data-urlencode 'query=sdp:lead_time:by_app' 2>/dev/null \
      | python3 -c "
import sys,json
r = json.load(sys.stdin)
if r.get('data',{}).get('result'):
  for item in sorted(r['data']['result'], key=lambda x: float(x['value'][1])):
    app = item['metric']['app']; val = float(item['value'][1])
    print(f'  {app}: {val:.0f}s' if val < 60 else f'  {app}: {val/60:.1f}min')
" 2>/dev/null || true
  fi
fi

echo ""
log "========================================="
log "Demo ready!"
log "========================================="
echo ""
echo "  Grafana:  https://${GRAFANA_ROUTE:-pending}"
echo "  Login:    admin / \$PELORUS_PASSWORD"
echo "  Range:    Last 6 months"
echo ""
echo "  To re-seed data:  ./demo/setup-demo.sh --seed"
echo ""
