# Values file for exporter helm chart
app_name: deploytime-exporter
source_context_dir: exporters/
extraEnv:
- name: APP_FILE
  value: deploytime/app.py
source_ref: master
source_url: https://github.com/redhat-cop/pelorus.git
