# For details refer to the documentation:
#       https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters

apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: pelorus
type: Opaque
stringData:
  GIT_USER: "pelorus@jira.username.io"             # Github Username
  GIT_TOKEN: "secret_token"                        # Github Token
