# For details refer to the documentation:
#       https://pelorus.readthedocs.io/en/latest/Configuration/#configuring-exporters

apiVersion: v1
kind: Secret
metadata:
  name: jira-secret
  namespace: pelorus
type: Opaque
stringData:
  SERVER: "https://pelorustest.atlassian.net/" # Provide JIRA Server endpoint
  USER: "pelorus@jira.username.io"             # JIRA Username
  TOKEN: "secret_token"                        # JIRA Token
