# Values file for exporter helm chart
app_name: committime-exporter
env_from_secrets: 
- github-secret
source_context_dir: exporters/
app_file: committime/app.py
source_ref: master
source_url: https://github.com/redhat-cop/pelorus.git
