{{- define "exporters.deploymentconfig" }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/name: {{ .app_name }}
    application: {{ .app_name }}
  name: {{ .app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app.kubernetes.io/name: {{ .app_name }}
    app: {{ .app_name }}
    deploymentconfig: {{ .app_name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .app_name }}
        app: {{ .app_name }}
        deploymentconfig: {{ .app_name }}
        application: {{ .app_name }}
        pelorus.konveyor.io/exporter-type: {{ .exporter_type | default "generic-exporter" }}
    spec:
      containers:
      - name: {{ .app_name }}
        imagePullPolicy: Always
        envFrom:
      {{- range .env_from_configmaps | default (list "default-pelorus-config" "default-deploytime-config") }}
        - configMapRef:
            name: {{ . }}
      {{- end}}
      {{- range .env_from_secrets }}
        - secretRef:
            name: {{ . }}
      {{- end}}
        env:
{{- if .exporter_type }}
        - name: APP_FILE
          value: {{ .exporter_type }}/app.py
{{- end }}
{{- if .extraEnv }}
{{ toYaml .extraEnv | indent 8 }}
{{- end }}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      serviceAccount: pelorus-exporter
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .app_name }}
      from:
        kind: ImageStreamTag
{{- if or .source_ref .source_url }}
        name: {{ .app_name }}:latest
{{- else }}
        name: {{ .app_name }}:{{ .image_tag | default "stable" }}
{{- end }}
    type: ImageChange
{{- end }}
