name: Pelorus Exporter Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - samples/
      - charts/
      - demo/
      - docs/
      - labs/
      - tests/
      - storage/
      - chart_schema.yaml
      - CONTRIBUTING.md

env:
  imageregistry: 'quay.io'
  imagenamespace: 'pelorus'
  latesttag: latest
  s2i_log_level: 2

jobs:
  build-committime:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          builder_image: 'registry.access.redhat.com/ubi8/python-39'
          image: 'committime-exporter'
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}
          path_context: 'exporters/committime'

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

  build-deploytime:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          builder_image: 'registry.access.redhat.com/ubi8/python-39'
          image: 'deploytime-exporter'
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}
          path_context: 'exporters/deploytime'

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

  build-failure:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        id: build-exporter
        uses: redhat-actions/s2i-build@v2
        with:
          builder_image: 'registry.access.redhat.com/ubi8/python-39'
          image: 'failure-exporter'
          tags: ${{ env.latesttag }} ${{ github.sha }}
          log_level: ${{ env.s2i_log_level }}
          path_context: 'exporters/failure'

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-exporter.outputs.image }}
          tags: ${{ steps.build-exporter.outputs.tags }}
          registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
