name: Charts check
on:
  push:
    branches: [ master ]
    paths:
      - 'exporters/**'
      - 'charts/**'
      - 'pelorus-operator/**'
      - '.github/workflows/chart-check.yml'
      - 'lintconf.yaml'
      - 'Makefile'

  pull_request:
    branches: [ master ]
    paths:
      - 'exporters/**'
      - 'charts/**'
      - 'pelorus-operator/**'
      - '.github/workflows/chart-check.yml'
      - 'lintconf.yaml'
      - 'Makefile'

jobs:
  chart-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Charts check
        run: make chart-check
