name: Chart Lint

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'exporters/**'
      - 'pelorus-operator/helm-charts/**'
      - 'pelorus-operator/**'
      - '.github/workflows/chart-lint.yml'
      - 'lintconf.yaml'
      - 'Makefile'

  pull_request:
    branches: [ main ]
    paths:
      - 'exporters/**'
      - 'pelorus-operator/helm-charts/**'
      - 'pelorus-operator/**'
      - '.github/workflows/chart-lint.yml'
      - 'lintconf.yaml'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Lint charts
        run: make chart-lint
