name: Check Python dependencies
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  check-python-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: | 
          make dev-env
          . .venv/bin/activate
          poetry install

      - name: Check if project's Python dependencies files are up to date
        run: |
          make update-requirements
          test -z "$(git status --short)"
