name: Check for updates in Documentation index file

on:
  pull_request:
    branches:
      - master
    paths:
      - docs/index.md
      - README.md

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Check for updates in Documentation index file
        run: make doc-check
