name: Continuos Integration

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'
  schedule:
    - cron:  '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  project-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make dev-env

      - name: Check OpenShift versions used by the project
        run: make openshift-check-versions
