name: Continuous Delivery

on:
  push:
    branches:
      - test-images-**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test if logic
      if: ""
      run: |
        echo "it ran!"