name: Conftest

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '_test/**'
      - 'pelorus-operator/helm-charts/**'
      - '.github/workflows/conftest.yml'
      - 'Makefile'

  pull_request:
    branches: [ main ]
    paths:
      - '_test/**'
      - 'pelorus-operator/helm-charts/**'
      - '.github/workflows/conftest.yml'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          make dev-env

      - name: Run conf-tests
        run: |
          make conf-tests
