name: Conftest

on:
  push:
    paths:
      - '_test/**'
      - 'charts/**'
  pull_request:
    paths:
      - '_test/**'
      - 'charts/**'

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@master
        with:
          tests: _test/conftest.sh