name: Integration Tests

permissions:
  contents: read
  actions: read

on:
  workflow_run:
    workflows: [Trigger test images]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  setup:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      branch_ref: ${{ steps.variables.outputs.branch_ref }}
      pr_type: ${{ steps.variables.outputs.pr_type }}
    steps:
      - name: Download trigger information
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: trigger-test-images.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: trigger-information
          path: ./

      - name: Store variables
        id: variables
        run: |
          echo "branch_ref=$(jq -r '.branch_ref' trigger-information.json)" >> "$GITHUB_OUTPUT"
          echo "pr_type=$(jq -r '.pr_type' trigger-information.json)" >> "$GITHUB_OUTPUT"

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ needs.setup.outputs.pr_type != 'closed' }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.branch_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Install dependencies
        run: make dev-env

      - name: Run integration-test
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          PAGER_DUTY_TOKEN: ${{ secrets.PAGER_DUTY_TOKEN }}
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: make integration-tests
