name: Check Python Formatting
on:
  pull_request:
    paths:
      - 'exporters/**'
      - 'pyproject.toml'
      - 'scripts/format'
      - '.github/workflows/python-formatting.yml'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exporters/requirements.txt
          pip install -r exporters/requirements-dev.txt
      - name: Check for formatting
        run: ./scripts/format --check