name: Check Python Formatting
on:
  pull_request:
    paths:
      - 'exporters/**'
      - 'pyproject.toml'
      - 'scripts/format'
      - '.github/workflows/python-formatting.yml'

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check for formatting
        run: make format-check
