name: Check Python Formatting & Linting
on: pull_request

jobs:
  lint-and-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # TODO: make it only check out only the latest commits from both branches and diff them.
        # Right now, without this, it thinks no code has changed.
      - name: check for where stuff is installed
        run: ls -alR /opt/hostedtoolcache/Python/
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: check for where stuff is installed
        run: ls -alR /opt/hostedtoolcache/Python/
      - name: Cache pip installs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('exporters/requirements*.txt') }}
      - name: Install dependencies
        run: |
          pip install -r exporters/requirements.txt
          pip install -r exporters/requirements-dev.txt

      - name: Check for formatting
        id: formatting
        continue-on-error: true
        run: ./scripts/formatchanged --check --head "${{ github.event.pull_request.head.sha }}" --base "${{ github.event.pull_request.base.sha }}"
      - name: Run pylava for linting
        id: linting
        continue-on-error: true
        run: pylava
      - name: Fail if formatting or linting failed
        if: ${{ steps.formatting.outcome == 'failure' || steps.linting.outcome == 'failure' }}
        run: exit 1