name: Pelorus Release

on:
  release:
    types:
      - prereleased
      - released

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout opl-content-api
        uses: actions/checkout@v2

      - name: Tag committime with (pre)release version
        uses: tinact/docker.image-retag@1.0.2
        with:
          image_name: pelorus/committime-exporter
          image_old_tag: ${{ github.sha }}
          image_new_tag: ${{ github.event.release.tag_name }}
          registry: quay.io
          registry_username: ${{ secrets.QUAY_USERNAME }}
          registry_password: ${{ secrets.QUAY_PASSWORD }}

      - name: Tag deploytime with (pre)released version
        uses: tinact/docker.image-retag@1.0.2
        with:
          image_name: pelorus/deploytime-exporter
          image_old_tag: ${{ github.sha }}
          image_new_tag: ${{ github.event.release.tag_name }}
          registry: quay.io
          registry_username: ${{ secrets.QUAY_USERNAME }}
          registry_password: ${{ secrets.QUAY_PASSWORD }}

      - name: Tag failure with (pre)released version
        uses: tinact/docker.image-retag@1.0.2
        with:
          image_name: pelorus/failure-exporter
          image_old_tag: ${{ github.sha }}
          image_new_tag: ${{ github.event.release.tag_name }}
          registry: quay.io
          registry_username: ${{ secrets.QUAY_USERNAME }}
          registry_password: ${{ secrets.QUAY_PASSWORD }}
