name: Shellcheck Tests
on:
  push:
    # Sync with Makefile and SHELL_SCRIPTS
    paths:
      - 'demo/demo-tekton'
      - 'scripts/create_release_pr'
      - 'scripts/install_dev_tools'
      - 'scripts/pre-commit'
      - 'scripts/run-mockoon-tests'
      - 'scripts/setup-pre-commit-hook'
      - 'scripts/run-pelorus-e2e-tests'

  pull_request:
    # Sync with Makefile and SHELL_SCRIPTS
    paths:
      - 'demo/demo-tekton'
      - 'scripts/create_release_pr'
      - 'scripts/install_dev_tools'
      - 'scripts/pre-commit'
      - 'scripts/run-mockoon-tests'
      - 'scripts/setup-pre-commit-hook'
      - 'scripts/run-pelorus-e2e-tests'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Test with shellcheck
        run: |
          make shellcheck
