name: Shellcheck Tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'Makefile'
      - '**.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'Makefile'
      - '**.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            pyproject.toml

      - name: Test with shellcheck
        run: make shellcheck
