name: Trigger test images

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
    - main
    - test-images-**
  pull_request:
    branches: [ main ]
    paths:
      - 'exporters/**'
      - 'pelorus-operator/helm-charts/**'
      - 'pelorus-operator/**'
      - '.github/workflows/trigger-test-images.yml'
    types: [opened, reopened, synchronize, closed]

jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - id: sha
        run: echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  generate-jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: get-short-sha
    steps:
      - name: Create json file
        env:
          BRANCH_REF: ${{ github.ref }}
          PR_TYPE: ${{ github.event.action }}
          PR_NUMBER: ${{ github.event.number }}
          COMMIT_HASH: ${{ needs.get-short-sha.outputs.sha }}
        run: |
          jq -n \
            --arg branch_ref "$BRANCH_REF" \
            --arg pr_type "$PR_TYPE" \
            --arg pr_number "$PR_NUMBER" \
            --arg commit_hash "$COMMIT_HASH" \
            '{branch_ref: $branch_ref, pr_type: $pr_type, pr_number: $pr_number, commit_hash: $commit_hash}' \
            > trigger-information.json

      - uses: actions/upload-artifact@v4
        with:
          name: trigger-information
          path: ./trigger-information.json
