{{- define "exporters.deploymentconfig" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .app_name }}
    application: {{ .app_name }}
  name: {{ .app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .app_name }}
      app: {{ .app_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .app_name }}
        app: {{ .app_name }}
        pelorus.dora-metrics.io/exporter-type: {{ .exporter_type | default "generic-exporter" }}
    spec:
      serviceAccount: pelorus-exporter
      volumes:
        {{- range $config := .custom_certs }}
        - name: custom-cert-volume-{{$config.map_name}}
          configMap:
            name: {{ $config.map_name }}
        {{- end }}
      containers:
        - name: {{ .app_name }}
          imagePullPolicy: Always
          image: quay.io/pelorus/pelorus-{{ .exporter_type }}-exporter:{{ .image_tag | default "v2.0.13-rc.5" }}
          volumeMounts:
            {{- range $config := .custom_certs }}
            - name: custom-cert-volume-{{$config.map_name}}
              mountPath: /etc/pelorus/custom_certs/{{$config.map_name}}
            {{- end }}

          envFrom:
            {{- range .env_from_configmaps | default (list "default-pelorus-config" "default-deploytime-config") }}
            - configMapRef:
                name: {{ . }}
            {{- end }}

            {{- range .env_from_secrets }}
            - secretRef:
                name: {{ . }}
            {{- end}}
          env:
            {{- if .exporter_type }}
            - name: APP_FILE
              value: {{ .exporter_type }}/app.py
            {{- end }}

            {{- if and (not .source_ref) (not .source_url) }}
            - name: PELORUS_IMAGE_TAG
              {{- if .image_name }}
                {{- if contains ":" .image_name }}
              value: {{ .image_name }}
                {{- else }}
              value: {{ .image_name }}:{{ .image_tag | default "latest" }}
                {{- end }}
              {{- else }}
              value: quay.io/pelorus/pelorus-{{ .exporter_type }}-exporter:{{ .image_tag | default "v2.0.13-rc.5" }}
              {{- end }}
            {{- end }}

            {{- if .extraEnv }}
            {{- toYaml .extraEnv | nindent 12}}
            {{- end }}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
{{- end }}
