# These configmaps are not meant to be edited directly.
# To configure pelorus, you can create your own copies of these.
# See the documentation for details:
# https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusExporters/#env_from_configmaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-pelorus-config
data:
  PELORUS_DEFAULT_KEYWORD: "default"   # default  |  Other ConfigMap values "default" keyword
  APP_LABEL: "default"                 # app.kubernetes.io/name  |  Deploy and Commit time exporters - label key used to identify applications
  LOG_LEVEL: "default"                 # INFO  |  Log level, DEBUG, INFO, WARNING or ERROR
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-deploytime-config
data:
  PROD_LABEL: "default"    # "" | PROD_LABEL is ignored if NAMESPACES are provided
  NAMESPACES: "default"    # "" | Restricts the set of namespaces,  comma separated value "myapp-ns-dev,otherapp-ci"
