---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pelorus-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: pelorus-exporters
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: v1.1
  name: pelorus-exporter-{{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - replicationcontrollers
  - pods
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - list
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  - buildconfigs
  verbs:
  - list
  - get
- apiGroups:
  - image.openshift.io
  resources:
  - images
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: pelorus-exporters
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: v1.2
  name: pelorus-exporter-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pelorus-exporter-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: pelorus-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: pelorus-exporters-image-puller
    app.kubernetes.io/name: {{ .Release.Name }}-image-puller
    app.kubernetes.io/version: v1.2
  name: pelorus-exporter-image-puller-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: pelorus-exporter
  namespace: {{ .Release.Namespace }}
