#!/bin/bash

bump_version() {
    chart=${1}
    version=$(python _test/bump_version.py -i ${chart})
    sed -i "s/version:\ .*$/version:\ ${version}/" ${chart}/Chart.yaml
    echo "Updated chart ${chart} version to ${version}."
}

chart_lint=$(ct lint --remote upstream 2>&1)
failed=$?
failed_charts=$(echo "${chart_lint}" | sed -n 's/.*\(path:\ \"\)\(.*\)\".*Chart\ version.*$/\2/p')

if [ ${failed} -ne 0 ] && [ "${failed_charts}" != "" ]; then
    for chart in ${failed_charts}; do
        bump_version ${chart}
    done
    # Recursively call script to ensure tests pass now
    ./$0

    echo "Please re-commit."
    exit 1
fi
