# For details refer to the documentation:
#       https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusExporters/#env_from_configmaps

apiVersion: v1
kind: ConfigMap
metadata:
  name: pelorus-config
  namespace: pelorus
data:
  PELORUS_DEFAULT_KEYWORD: "default"   # default  |  Other ConfigMap values "default" keyword
  APP_LABEL: "default"                 # app.kubernetes.io/name  |  Deploy and Commit time exporters - label key used to identify applications
  LOG_LEVEL: "default"                 # INFO  |  Log level, DEBUG, INFO, WARNING or ERROR
